pipeline:
  build:
    image: node:8
    environment:
      - NODE_ENV=development
      - PORT=4000
      - JWT_MODE=hmac
      - JWT_SECRET=0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      - JWT_PRIVATE_KEY_PATH=private.key
      - JWT_PUBLIC_KEY_PATH=private.key.pub
      - JWT_TTL=3600
      - PG_DB=auth
      - PG_PORT=5432
      - PG_HOST=localhost
      - PG_USER=postgres
      - PG_PASSWD=postgres
      - MAILER_EMAIL_ID=''
      - MAILER_PASSWORD=testpass
      - MAILER_SERVICE_PROVIDER=Gmail
    commands:
      - yarn
      - yarn test:coverage
  publish-dev:
    image: plugins/docker
    repo: amidatech/auth-service
    tags: [ dev ]
    when:
      branch: develop
  publish-latest:
    image: plugins/docker
    repo: amidatech/auth-service
    tags: [ latest ]
    when:
      branch: master

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD=postgres
