FORMAT: 1A
HOST: http://docs.amidaauth.apiary.io/

# Amida Auth

This is an API allowing authentication and basic authorization using JSON Web Tokens.

# Group Miscellaneous

Resources related to utility actions, such as health checks.

## Health Check [/health-check]

### Show Health Check [GET]

# Group Users

Resources related to User identity management, such as creating and updating Users.
This includes editing user scopes for authorization purposes.

## Users Collection [/user]

### List All Users [GET]

### Create New User [POST]

## Single User Actions [/user/:userId]

### Get Single User [GET]

### Update User [PUT]

### Delete User [DELETE]

## User Scopes [/user/scopes/:userId]

### Update User Scopes [PUT]

## Me [/user/me]

### Get Logged-in User [GET]

# Group Auth

Resources related to authentication, such as login and password changes.

## Login [/auth/login]

### Authenticate For JWT [POST]

## Update Password [/auth/update-password]

### Submit New Password  [POST]

## Reset Password Initiation [/auth/reset-password]

### Submit Reset Password Request [POST]

## Reset Password [/auth/reset-password/:token]

### Submit New Password [POST]