FORMAT: 1A

# Amida Auth
This is an API allowing authentication and basic authorization using JSON Web Tokens.

# Group Miscellaneous
Resources related to utility actions, such as health checks.

## Health Check [/health-check]

### Show Health Check [GET]

+ Response 200

    + Body

        {
            "status": "ok"
        }


# Group Users
Resources related to User identity management, such as creating and updating Users.
This includes editing user scopes for authorization purposes.
