FORMAT: 1A

# Amida Auth
This is an API allowing authentication and basic authorization using JSON Web Tokens.

# Group Miscellaneous
Resources related to utility actions, such as health checks.

## Users Collection [/user]

### List All Users [GET]
Get a complete list of users. Must be admin.

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXVpZCI6IjBhMTU0MWM4LTM3MDUtNDkyZC1iYTExLTM1NjJhZGQ5NmIzZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwic2NvcGVzIjpbImFkbWluIl0sInZlcmlmaWVkQ29udGFjdE1ldGhvZHMiOltdLCJpYXQiOjE1NjY1MDcwODEsImV4cCI6MTU2NjUxMDY4MX0.aohfoFpZkXWn5q3TelOscmTsm3MP7liCzuBaR9jRl_g

+ Response 200 (application/json; charset=utf-8)

    + Body

            [{"id":1,"username":"<>","email":"<>", "uuid":"<>"}]

