---
- name: logging | import repo gpg key
  rpm_key:
    state: present
    key: http://packages.elastic.co/GPG-KEY-elasticsearch

- name: logging | set up repo
  yum_repository:
    name: beats
    description: Elastic Beats Repository
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    enabled: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes

# beat doesn't support intermediate certs so this is needed
# to make letsencrypt work
- name: logging | copy ssl cert script
  template:
    src: logging_ssl_cert.sh
    dest: /usr/local/bin/logging_ssl_cert.sh

- name: logging | run ssl cert script
  command: sh /usr/local/bin/logging_ssl_cert.sh

- include: metricbeat.yml

- include: filebeat.yml
